#!/usr/bin/zsh
# This hook is sourced after this virtualenv is activated.
#
#
#
#
export PROJECT_PATH=$HOME/projects/octopus
export SOURCE_PATH=$HOME/projects/octopus/
export PYTHONPATH=$PYTHONPATH:$SOURCE_PATH

cd $PROJECT_PATH




